{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgdown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pkgdown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pkgdown/pkgdown_{{ version }}.tar.gz
  sha256: eff0561f98027b96373dbafc6ca28c9def61afc0b0174452fd7de0651b1b230f

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-callr >=2.0.2
    - r-cli
    - r-crayon
    - r-desc
    - r-digest
    - r-evaluate
    - r-fansi
    - r-fs >=1.2.0
    - r-highlight
    - r-httr
    - r-magrittr
    - r-memoise
    - r-openssl
    - r-processx
    - r-purrr
    - r-rematch2
    - r-rlang >=0.3.0
    - r-rmarkdown >=1.1.9007
    - r-rstudioapi
    - r-tibble
    - r-whisker
    - r-withr
    - r-xml2 >=1.1.1
    - r-yaml
  run:
    - r-base
    - r-mass
    - r-callr >=2.0.2
    - r-cli
    - r-crayon
    - r-desc
    - r-digest
    - r-evaluate
    - r-fansi
    - r-fs >=1.2.0
    - r-highlight
    - r-httr
    - r-magrittr
    - r-memoise
    - r-openssl
    - r-processx
    - r-purrr
    - r-rematch2
    - r-rlang >=0.3.0
    - r-rmarkdown >=1.1.9007
    - r-rstudioapi
    - r-tibble
    - r-whisker
    - r-withr
    - r-xml2 >=1.1.1
    - r-yaml

test:
  commands:
    - $R -e "library('pkgdown')"           # [not win]
    - "\"%R%\" -e \"library('pkgdown')\""  # [win]

about:
  home: https://pkgdown.r-lib.org, https://github.com/r-lib/pkgdown
  license: MIT
  summary: Generate an attractive and useful website from a source package. 'pkgdown' converts your documentation, vignettes, 'README', and more to  'HTML' making
    it easy to share information about your package online.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pkgdown
# Title: Make Static HTML Documentation for a Package
# Version: 1.4.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre"),  comment = c(ORCID = "0000-0003-4757-117X") ), person("Jay", "Hesselberth", role = "aut",  comment = c(ORCID = "0000-0002-6299-179X") ), person("RStudio", role = c("cph", "fnd")) )
# Description: Generate an attractive and useful website from a source package. 'pkgdown' converts your documentation, vignettes, 'README', and more to  'HTML' making it easy to share information about your package online.
# License: MIT + file LICENSE
# URL: https://pkgdown.r-lib.org, https://github.com/r-lib/pkgdown
# BugReports: https://github.com/r-lib/pkgdown/issues
# Depends: R (>= 3.1.0)
# Imports: callr (>= 2.0.2), cli, crayon, desc, digest, evaluate, fs (>= 1.2.0), fansi, highlight, httr, magrittr, MASS, memoise, openssl, purrr, processx, rematch2, rlang (>= 0.3.0), rmarkdown (>= 1.1.9007), rstudioapi, tibble, tools, whisker, withr, xml2 (>= 1.1.1), yaml
# Suggests: covr, htmlwidgets, jsonlite, knitr, leaflet, pkgload (>= 1.0.2), testthat (>= 2.1.0), rticles, rsconnect
# VignetteBuilder: knitr
# SystemRequirements: pandoc
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-09-03 16:13:41 UTC; hadley
# Author: Hadley Wickham [aut, cre] (<https://orcid.org/0000-0003-4757-117X>), Jay Hesselberth [aut] (<https://orcid.org/0000-0002-6299-179X>), RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-03 16:40:02 UTC
